import { useEffect, useState } from "react";
import { useLocation } from "react-router-dom";

import StandardPage from "../components/StandardPage";
import { api } from "../lib/api";

const protectedTerms=["CFP Advantage","ADV Strength Rating (ADV SRS)","ADV Expected Margin","ADV Deserved Margin","ADV Strength of Schedule","Control Rate","Control Creation","Control Denial","Control Finish","Control Drive Shutout Rate","Control Pressure","Scoreboard Control Gap","Contextual Football Profile","Results Profile","Talent Yield Index","Bracket Room","Bracket Path Probability"];

function PolicySection({id,eyebrow,title,children}){return <section id={id} className="workspace-view static-page"><div className="panel-heading"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div></div><div className="legal-copy legal-sections">{children}</div></section>}

function LegalPage(){
  const{hash}=useLocation();const[legal,setLegal]=useState({});const[accepted,setAccepted]=useState(()=>localStorage.getItem("cfpAdvantageTermsAccepted")==="true");
  useEffect(()=>{api("/api/legal/acknowledgement").then(setLegal).catch(()=>{})},[]);
  useEffect(()=>{if(hash)requestAnimationFrame(()=>document.getElementById(hash.slice(1))?.scrollIntoView())},[hash]);
  function accept(){localStorage.setItem("cfpAdvantageTermsAccepted","true");localStorage.setItem("cfpAdvantageTermsVersion",legal.terms_version||"current");localStorage.setItem("cfpAdvantageTermsAcceptedAt",new Date().toISOString());setAccepted(true)}
  return <StandardPage className="legal-page-shell">
    <PolicySection id="acknowledgement" eyebrow="Browser Acknowledgement" title="CFP Advantage Terms"><p>{legal.message||"Review the policies below before using CFP Advantage."}</p><p>Terms version: <strong>{legal.terms_version||"Current"}</strong></p><p>Local browser storage remembers acknowledgement and display preferences on this device. Clearing browser data may reset them.</p><button className="primary-action" type="button" onClick={accept} disabled={accepted}>{accepted?"Accepted In This Browser":"Accept In This Browser"}</button></PolicySection>
    <PolicySection id="disclaimer" eyebrow="Site Disclaimer" title="Informational Analytics Only"><p>CFP Advantage provides sports analytics, projections, rankings, probability estimates, historical performance data, and matchup context for informational and educational purposes only.</p><p>CFP Advantage does not accept wagers, place bets, facilitate gambling transactions, or provide financial, gambling, or legal advice. Model outputs are estimates based on available data and historical behavior; they are not guarantees.</p><p>Football outcomes are uncertain. Users are responsible for their decisions and for complying with applicable laws in their jurisdiction. Past performance does not guarantee future results.</p></PolicySection>
    <PolicySection id="terms" eyebrow="Terms Of Use" title="Use Of CFP Advantage"><p><strong>Effective date:</strong> May 30, 2026<br/><strong>Contact:</strong> <a href="mailto:support@cfpadvantage.com">support@cfpadvantage.com</a></p><h3>1. Purpose</h3><p>CFP Advantage supplies college-football analytics, team ratings, model-generated insights, matchup reports, rankings, and historical context for informational use.</p><h3>2. No Advice Or Guarantees</h3><p>Projections, probabilities, ratings, context labels, and risk flags are estimates. CFP Advantage does not guarantee winners, margins, financial outcomes, availability, completeness, or future performance.</p><h3>3. User Responsibility</h3><p>You are responsible for how you interpret the information, every decision you make from it, and whether your use is lawful where you live.</p><h3>4. Eligibility</h3><p>You must be at least 13 to browse the free site. Payment transactions require age 18 or the age of majority in your jurisdiction, whichever is higher.</p><h3>5. Payments, Cancellation, And Refunds</h3><p>Checkout states the price and payment terms. Cancellation stops future recurring billing. Prior payments are handled under the refund policy below.</p><h3>6. Features And Model Changes</h3><p>Features, data fields, reports, and models may change as the product develops. Published pregame receipts are preserved and are not rewritten after results are known.</p><h3>7. Proprietary Product</h3><p>CFP Advantage models, code, reports, visual designs, written content, data structures, metric names, context labels, and model-derived terminology are proprietary unless stated otherwise.</p><ul className="legal-term-list">{protectedTerms.map((term)=><li key={term}>{term}</li>)}</ul><p>You may not scrape, reproduce, resell, republish, reverse engineer, or commercially exploit this material without written permission.</p><h3>8. Prohibited Use</h3><p>Do not access restricted systems, share restricted content, scrape at scale, extract proprietary formulas, misrepresent CFP Advantage content, or use the service unlawfully.</p><h3>9. Third-Party Services</h3><p>Hosting, data, analytics, email, and payment providers may have their own policies. External links lead to services CFP Advantage does not control.</p><h3>10. Liability And Warranties</h3><p>The service is provided “as is” and “as available.” To the fullest extent permitted by law, CFP Advantage is not liable for damages arising from use of the site or its information.</p><h3>11. Changes And Contact</h3><p>Updated terms will be posted with a revised date. Questions may be sent to support@cfpadvantage.com.</p></PolicySection>
    <PolicySection id="privacy" eyebrow="Privacy Policy" title="Data And Browser Storage"><p><strong>Effective date:</strong> September 16, 2026</p><h3>Information We Collect</h3><p>Free browsing does not require an account. CFP Advantage may receive information you submit for support, email preferences, giveaways, or payments, plus ordinary technical and usage information used to operate and secure the site.</p><h3>Payments</h3><p>CFP Advantage does not directly store full card numbers. Payment credentials are handled by third-party processors.</p><h3>Local Storage And Cookies</h3><p>The site may use browser storage or similar technology to remember terms acceptance, theme, selected views, and basic preferences. Clearing browser data resets those preferences.</p><h3>Use And Sharing</h3><p>Information may be used to operate the service, respond to support, process payments, analyze performance, prevent abuse, and maintain security. CFP Advantage does not sell personal information. Limited data may be shared with service providers that perform those functions.</p><h3>Retention, Choices, And Children</h3><p>Information is retained as needed for services, legal duties, security, and records. Requests to correct or delete eligible information may be sent to support@cfpadvantage.com. CFP Advantage is intended for people age 13 and older.</p></PolicySection>
    <PolicySection id="refunds" eyebrow="Refund Policy" title="Billing And Subscription Terms"><p><strong>Effective date:</strong> May 30, 2026</p><h3>Billing And Renewal</h3><p>Prices, billing periods, included features, and renewal terms are displayed before purchase. Recurring plans renew unless canceled before the renewal date.</p><h3>Cancellation</h3><p>Cancellation stops future billing and does not automatically refund prior payments.</p><h3>Refunds</h3><p>Unless checkout states otherwise, payments are non-refundable after access is delivered. CFP Advantage may consider duplicate charges, billing errors, accidental duplicate purchases, or unresolved technical-access failures. Contact support@cfpadvantage.com.</p><h3>Feature Changes</h3><p>Model corrections, scoring refinements, data updates, and changes to features or reports do not automatically create a refund entitlement.</p></PolicySection>
  </StandardPage>
}

export default LegalPage;
