import StandardPage from "../components/StandardPage";

const releases = [
  {date:"October 2, 2026",title:"CFP Advantage 2.4",items:["Added a plain-language matchup read that answers who ADV favors, why, and what could turn the game before presenting the full analytical framework.","Renamed the detailed matchup action to Full Breakdown and retained the complete ratings, Control Framework, recent form, talent context, and familiar-stat views behind it.","Added plain-language translations above proprietary metric names so new fans can understand the football meaning while experienced users can inspect the underlying evidence."]},
  {date:"October 2, 2026",title:"CFP Advantage 2.3",items:["Added a crawlable Public Model Record that separates historical evidence, graded 2026 results, pending projections, and development-validation limits.","Published a machine-readable validation record with weekly grades and links to immutable public receipts.","Added current record figures and validation scope to the homepage crawler snapshot, AI feed, sitemap, and llms.txt while explicitly stating that no completed independent third-party validation is claimed."]},
  {date:"October 2, 2026",title:"CFP Advantage 2.2",items:["Added the public Metric Relationships study with movement charts, a side-by-side comparison matrix, and held-out evidence showing what ADV retains beyond common advanced statistics.","Restored current-week final scores and provisional model results to the Matchups page without changing frozen picks or certified grades.","Improved dark-mode contrast across the About page, Metrics Guide, and Metric Relationships evidence tables.","Expanded the sitemap and AI-readable discovery layer to include the Metric Relationships page and its machine-readable dataset."]},
  {date:"October 2, 2026",title:"CFP Advantage 2.1",items:["Improved mobile alignment for Games of the Week, matchup cards, logos, and ranking tags.","Added an AI-readable public discovery layer with structured team, matchup, and current-week resources.","Improved team recaps, player-stat contrast, framework-card behavior, and dark-mode presentation."]},
  {date:"September 27, 2026",title:"CFP Advantage 2.0",items:["Launched the React V2 public site with the full weekly matchup slate, live scoreboard, team profiles, player statistics, recaps, and Bracket Room.","Preserved the 2026 development-validation language and the existing public receipt history."]},
  {date:"September 22, 2026",title:"Matchup Context Repair",items:["Recent Form and Talent Yield now use the same certified common-cutoff context as team profiles.","All Week 4 ratings, winners, margins, and published receipts remained unchanged.","The Learning Hub and ADV Gridiron Report were retired until stronger supporting research is ready."]},
  {date:"September 19, 2026",title:"2026 Development Model",items:["The original frozen validation stopped after an early-season opponent-adjustment defect was found.","Weeks 1–3 receipts and grades remain preserved exactly as published.","Week 4 forward uses the corrected prior-regularized SRS system and retained universal margin translation; clean prospective validation restarts in 2027."]},
  {date:"September 3, 2026",title:"CFP Advantage 1.1",items:["Expanded team profiles, recaps, live scores, and schedule context.","Added shareable Framework Cards and clearer metric guidance.","Established 2016 as the first public season with complete Control Framework coverage."]},
];
function UpdatesPage(){return <StandardPage><section className="insight-panel updates-page"><p className="eyebrow">Release Notes</p><h2>Product Updates</h2><div className="release-list">{releases.map((release)=><article className="context-callout release-note" key={release.date}><p className="eyebrow">{release.date}</p><h3>{release.title}</h3><ul>{release.items.map((item)=><li key={item}>{item}</li>)}</ul></article>)}</div></section></StandardPage>}
export default UpdatesPage;
